package com.intuit.quickbase.devint;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.tuple.ImmutablePair;
import org.apache.commons.lang3.tuple.Pair;

public class ConcreteStatService implements IStatService {

	@Override
	/**
	 * Returns an unordered list of countries and their populations
	 */
	public List<Pair<String, Integer>> GetCountryPopulations() {
		List<Pair<String, Integer>> output = new ArrayList<Pair<String, Integer>>();
		
		// Pretend this calls a REST API somewhere
		output.add(new ImmutablePair<String, Integer>("Bosnia and Herzegovina",3844046));
		output.add(new ImmutablePair<String, Integer>("Republic of the Congo",3758678));
		output.add(new ImmutablePair<String, Integer>("Republic of China (Taiwan)",23162120));
		output.add(new ImmutablePair<String, Integer>("Ethiopia",83483000));
		output.add(new ImmutablePair<String, Integer>("Argentina",40518951));
		output.add(new ImmutablePair<String, Integer>("Cyprus",1102677));
		output.add(new ImmutablePair<String, Integer>("Uruguay",3356584));
		output.add(new ImmutablePair<String, Integer>("India",1182105000));
		output.add(new ImmutablePair<String, Integer>("United Kingdom",62026962));
		output.add(new ImmutablePair<String, Integer>("Romania",21462186));
		output.add(new ImmutablePair<String, Integer>("Sri Lanka",20653000));
		output.add(new ImmutablePair<String, Integer>("Mongolia",2780800));
		output.add(new ImmutablePair<String, Integer>("East Timor",1149028));
		output.add(new ImmutablePair<String, Integer>("South Africa",49991300));
		output.add(new ImmutablePair<String, Integer>("Somalia",9358602));
		output.add(new ImmutablePair<String, Integer>("Austria",8375290));
		output.add(new ImmutablePair<String, Integer>("Uganda",31784600));
		output.add(new ImmutablePair<String, Integer>("Poland",38167329));
		output.add(new ImmutablePair<String, Integer>("Switzerland",7785806));
		output.add(new ImmutablePair<String, Integer>("Serbia",7291436));
		output.add(new ImmutablePair<String, Integer>("Papua New Guinea",6744955));
		output.add(new ImmutablePair<String, Integer>("Eritrea",5223994));
		output.add(new ImmutablePair<String, Integer>("Guadeloupe (France)",404394));
		output.add(new ImmutablePair<String, Integer>("Costa Rica",4563539));
		output.add(new ImmutablePair<String, Integer>("Croatia",4425747));
		output.add(new ImmutablePair<String, Integer>("Spain",45989016));
		output.add(new ImmutablePair<String, Integer>("Thailand",63878267));
		output.add(new ImmutablePair<String, Integer>("Algeria",35978000));
		output.add(new ImmutablePair<String, Integer>("Guinea",10323755));
		output.add(new ImmutablePair<String, Integer>("Iran",74733230));
		output.add(new ImmutablePair<String, Integer>("Djibouti",879053));
		output.add(new ImmutablePair<String, Integer>("Comoros",675000));
		output.add(new ImmutablePair<String, Integer>("Iraq",32481000));
		output.add(new ImmutablePair<String, Integer>("Pakistan",173510000));
		output.add(new ImmutablePair<String, Integer>("Denmark",5534738));
		output.add(new ImmutablePair<String, Integer>("Norway",4858199));
		output.add(new ImmutablePair<String, Integer>("South Korea",49410366));
		output.add(new ImmutablePair<String, Integer>("Peru",29461933));
		output.add(new ImmutablePair<String, Integer>("New Zealand",4367800));
		output.add(new ImmutablePair<String, Integer>("Moldova",3563695));
		output.add(new ImmutablePair<String, Integer>("Egypt",78728000));
		output.add(new ImmutablePair<String, Integer>("Bahrain",1234571));
		output.add(new ImmutablePair<String, Integer>("North Korea",24325701));
		output.add(new ImmutablePair<String, Integer>("Laos",6230200));
		output.add(new ImmutablePair<String, Integer>("Ukraine",45782592));
		output.add(new ImmutablePair<String, Integer>("Chile",17094270));
		output.add(new ImmutablePair<String, Integer>("Mali",15370000));
		output.add(new ImmutablePair<String, Integer>("Greece",11305118));
		output.add(new ImmutablePair<String, Integer>("Armenia",3249482));
		output.add(new ImmutablePair<String, Integer>("Slovenia",2046976));
		output.add(new ImmutablePair<String, Integer>("Saint Vincent and the Grenadines",109284));
		output.add(new ImmutablePair<String, Integer>("Bhutan",695822));
		output.add(new ImmutablePair<String, Integer>("Aruba (Netherlands)",101484));
		output.add(new ImmutablePair<String, Integer>("Maldives",319738));
		output.add(new ImmutablePair<String, Integer>("Mayotte (France)",202000));
		output.add(new ImmutablePair<String, Integer>("Vietnam",86932500));
		output.add(new ImmutablePair<String, Integer>("Germany",81802257));
		output.add(new ImmutablePair<String, Integer>("Botswana",2029307));
		output.add(new ImmutablePair<String, Integer>("Togo",6191155));
		output.add(new ImmutablePair<String, Integer>("Luxembourg",502066));
		output.add(new ImmutablePair<String, Integer>("Panama",3504483));
		output.add(new ImmutablePair<String, Integer>("Trinidad and Tobago",1317714));
		output.add(new ImmutablePair<String, Integer>("France",62791013));
		output.add(new ImmutablePair<String, Integer>("The Bahamas",353658));
		output.add(new ImmutablePair<String, Integer>("Vanuatu",245036));
		output.add(new ImmutablePair<String, Integer>("Russia",142849472));
		output.add(new ImmutablePair<String, Integer>("Benin",9211741));
		output.add(new ImmutablePair<String, Integer>("Fiji",850700));
		output.add(new ImmutablePair<String, Integer>("Australia",22299800));
		output.add(new ImmutablePair<String, Integer>("Tanzania",43187823));
		output.add(new ImmutablePair<String, Integer>("Turkmenistan",5479800));
		output.add(new ImmutablePair<String, Integer>("Madagascar",20146442));
		output.add(new ImmutablePair<String, Integer>("Bulgaria",7563710));
		output.add(new ImmutablePair<String, Integer>("Gabon",1501266));
		output.add(new ImmutablePair<String, Integer>("Philippines",94013200));
		output.add(new ImmutablePair<String, Integer>("Israel",7623600));
		output.add(new ImmutablePair<String, Integer>("Federated States of Micronesia",102624));
		output.add(new ImmutablePair<String, Integer>("Sweden",9340682));
		output.add(new ImmutablePair<String, Integer>("Mauritius",1283415));
		output.add(new ImmutablePair<String, Integer>("Colombia",45508205));
		output.add(new ImmutablePair<String, Integer>("Grenada",109553));
		output.add(new ImmutablePair<String, Integer>("Democratic Republic of the Congo",67827496));
		output.add(new ImmutablePair<String, Integer>("Mozambique",22416881));
		output.add(new ImmutablePair<String, Integer>("Haiti",9855000));
		output.add(new ImmutablePair<String, Integer>("Sierra Leone",5835664));
		output.add(new ImmutablePair<String, Integer>("Singapore",5076700));
		output.add(new ImmutablePair<String, Integer>("Netherlands",16574989));
		output.add(new ImmutablePair<String, Integer>("Rwanda",10412820));
		output.add(new ImmutablePair<String, Integer>("Palestinian territories",4048403));
		output.add(new ImmutablePair<String, Integer>("Belize",312971));
		output.add(new ImmutablePair<String, Integer>("French Guiana (France)",232223));
		output.add(new ImmutablePair<String, Integer>("Ecuador",14483499));
		output.add(new ImmutablePair<String, Integer>("Latvia",2248374));
		output.add(new ImmutablePair<String, Integer>("Kosovo",2208107));
		output.add(new ImmutablePair<String, Integer>("U.S. Virgin Islands (US)",106267));
		output.add(new ImmutablePair<String, Integer>("Belarus",9480178));
		output.add(new ImmutablePair<String, Integer>("Myanmar",59780000));
		output.add(new ImmutablePair<String, Integer>("Mauritania",3217383));
		output.add(new ImmutablePair<String, Integer>("Malaysia",28334135));
		output.add(new ImmutablePair<String, Integer>("Dominican Republic",9884371));
		output.add(new ImmutablePair<String, Integer>("New Caledonia (France)",248000));
		output.add(new ImmutablePair<String, Integer>("Slovakia",5424925));
		output.add(new ImmutablePair<String, Integer>("Kyrgyzstan",5418300));
		output.add(new ImmutablePair<String, Integer>("Lithuania",3329039));
		output.add(new ImmutablePair<String, Integer>("United States of America",309349689));
		output.add(new ImmutablePair<String, Integer>("Lesotho",1891830));
		output.add(new ImmutablePair<String, Integer>("Barbados",276300));
		output.add(new ImmutablePair<String, Integer>("Morocco",31894000));
		output.add(new ImmutablePair<String, Integer>("Kenya",40862900));
		output.add(new ImmutablePair<String, Integer>("Mexico",112336538));
		output.add(new ImmutablePair<String, Integer>("Kuwait",3566437));
		output.add(new ImmutablePair<String, Integer>("Malta",414372));
		output.add(new ImmutablePair<String, Integer>("Ghana",24223431));
		output.add(new ImmutablePair<String, Integer>("Albania",3195000));
		output.add(new ImmutablePair<String, Integer>("Czech Republic",10506813));
		output.add(new ImmutablePair<String, Integer>("Montenegro",616411));
		output.add(new ImmutablePair<String, Integer>("Venezuela",28833845));
		output.add(new ImmutablePair<String, Integer>("El Salvador",6194126));
		output.add(new ImmutablePair<String, Integer>("Libya",6545619));
		output.add(new ImmutablePair<String, Integer>("Afghanistan",24485600));
		output.add(new ImmutablePair<String, Integer>("Zambia",13257269));
		output.add(new ImmutablePair<String, Integer>("Angola",18992708));
		output.add(new ImmutablePair<String, Integer>("Finland",5351427));
		output.add(new ImmutablePair<String, Integer>("Tunisia",10547100));
		output.add(new ImmutablePair<String, Integer>("Puerto Rico (US)",3721978));
		output.add(new ImmutablePair<String, Integer>("United Arab Emirates",8264070));
		output.add(new ImmutablePair<String, Integer>("Lebanon",3785655));
		output.add(new ImmutablePair<String, Integer>("Guam (US)",180865));
		output.add(new ImmutablePair<String, Integer>("Portugal",10637713));
		output.add(new ImmutablePair<String, Integer>("Nigeria",158258917));
		output.add(new ImmutablePair<String, Integer>("Western Sahara",530000));
		output.add(new ImmutablePair<String, Integer>("Macedonia",2052722));
		output.add(new ImmutablePair<String, Integer>("Suriname",531170));
		output.add(new ImmutablePair<String, Integer>("Canada",34108752));
		output.add(new ImmutablePair<String, Integer>("Nicaragua",5822265));
		output.add(new ImmutablePair<String, Integer>("Iceland",317630));
		output.add(new ImmutablePair<String, Integer>("Indonesia",237641326));
		output.add(new ImmutablePair<String, Integer>("Paraguay",6459727));
		output.add(new ImmutablePair<String, Integer>("Ireland",4467854));
		output.add(new ImmutablePair<String, Integer>("Liberia",4101767));
		output.add(new ImmutablePair<String, Integer>("Cambodia",14302779));
		output.add(new ImmutablePair<String, Integer>("Niger",15203822));
		output.add(new ImmutablePair<String, Integer>("Bangladesh",148600000));
		output.add(new ImmutablePair<String, Integer>("Nepal",28043744));
		output.add(new ImmutablePair<String, Integer>("Malawi",13947592));
		output.add(new ImmutablePair<String, Integer>("Yemen",23153982));
		output.add(new ImmutablePair<String, Integer>("Saudi Arabia",27136977));
		output.add(new ImmutablePair<String, Integer>("Italy",60340328));
		output.add(new ImmutablePair<String, Integer>("Sudan",42338426));
		output.add(new ImmutablePair<String, Integer>("Uzbekistan",28001400));
		output.add(new ImmutablePair<String, Integer>("Equatorial Guinea",1313000));
		output.add(new ImmutablePair<String, Integer>("Cuba",11241161));
		output.add(new ImmutablePair<String, Integer>("Georgia",4436391));
		output.add(new ImmutablePair<String, Integer>("Kiribati",100835));
		output.add(new ImmutablePair<String, Integer>("Brunei",414400));
		output.add(new ImmutablePair<String, Integer>("Senegal",12509434));
		output.add(new ImmutablePair<String, Integer>("Macau (PR China)",552300));
		output.add(new ImmutablePair<String, Integer>("Central African Republic",4505945));
		output.add(new ImmutablePair<String, Integer>("Syria",20619000));
		output.add(new ImmutablePair<String, Integer>("Zimbabwe",12644041));
		output.add(new ImmutablePair<String, Integer>("Honduras",8045990));
		output.add(new ImmutablePair<String, Integer>("Azerbaijan",8997586));
		output.add(new ImmutablePair<String, Integer>("Swaziland",1055506));
		output.add(new ImmutablePair<String, Integer>("Burundi",8518862));
		output.add(new ImmutablePair<String, Integer>("Tajikistan",7616400));
		output.add(new ImmutablePair<String, Integer>("Curacao (Netherlands)",142180));
		output.add(new ImmutablePair<String, Integer>("Namibia",2212037));
		output.add(new ImmutablePair<String, Integer>("Samoa",183123));
		output.add(new ImmutablePair<String, Integer>("Qatar",1699435));
		output.add(new ImmutablePair<String, Integer>("French Polynesia (France)",267000));
		output.add(new ImmutablePair<String, Integer>("Kazakhstan",16442000));
		output.add(new ImmutablePair<String, Integer>("Bolivia",10426154));
		output.add(new ImmutablePair<String, Integer>("Jordan",6113000));
		output.add(new ImmutablePair<String, Integer>("Guyana",761442));
		output.add(new ImmutablePair<String, Integer>("Hungary",10014324));
		output.add(new ImmutablePair<String, Integer>("Burkina Faso",15730977));
		output.add(new ImmutablePair<String, Integer>("Belgium",10839905));
		output.add(new ImmutablePair<String, Integer>("Saint Lucia",174000));
		output.add(new ImmutablePair<String, Integer>("Jamaica",2701200));
		output.add(new ImmutablePair<String, Integer>("Cameroon",19958352));
		output.add(new ImmutablePair<String, Integer>("Hong Kong (PR China)",7024200));
		output.add(new ImmutablePair<String, Integer>("Cape Verde",512582));
		output.add(new ImmutablePair<String, Integer>("Guatemala",14361666));
		output.add(new ImmutablePair<String, Integer>("Martinique (France)",399637));
		output.add(new ImmutablePair<String, Integer>("Guinea-Bissau",1647380));
		output.add(new ImmutablePair<String, Integer>("Chad",11714904));
		output.add(new ImmutablePair<String, Integer>("Japan",128056000));
		output.add(new ImmutablePair<String, Integer>("The Gambia",1750732));
		output.add(new ImmutablePair<String, Integer>("Estonia",1340127));
		return output;
	}

}
